### ISSUE TITLE
AttributeError: 'FakeVirtualEnv' object has no attribute '_getenv'

### ISSUE THREAD

**Issue by jayvdb** [ionelmc/python-tax#1]
It appears to be incompatible with tox 3.7.0

```py
  File "/home/abuild/rpmbuild/BUILD/tax-1.0.0/src/tax/session.py", line 30, in _pcall
    env = self._getenv(testcommand=testcommand)
AttributeError: 'FakeVirtualEnv' object has no attribute '_getenv'
```

Also it should be including a dependency on tox in its setup.py, now with a version constraint for the versions of tox which did work correctly.

**Comment by ionelmc** [comment]
So I'm abandoning this project - it's a pain in the ass to maintain. This should be implemented as a tox plugin instead (since recent versions have the necessary hooks).
